### ISSUE TITLE
Add Master Mode compatibility

### ISSUE THREAD

**Issue by d4mation** [lud99/botw-unexplored#1]
On my "Normal Mode" save file, I have found all the Koroks and Locations already. However, on my Master Mode save file I have not.

After you choose your Profile, it immediately loads the "Normal Mode" save file with no way to switch to Master Mode. If there were a way to choose which one to load that would be really nice.

**Comment by lud99** [comment]
This is definetly something I'll add, it didn't even cross my mind. 

So the master mode save file is stored in the folders 6 and 7 in the savefile directory. One of them is supposed to be an auto save, and the other one a "normal/manual" save. But the problem is I don't know which one is which. So do you by any chance know which one should be read to have the most recent version? 

My guess is that 6 is the most recent, because the normal save's most recent version has the lowest number (0). But thats only a guess.

**Comment by lud99** [comment]
I opened both of my master mode savefiles into your web app, and it seems like 7 is the most recent version. I should've probably thought about checking before asking, but hey, that's how it is sometimes!

**Comment by d4mation** [comment]
I haven't double-checked this myself, but it looks like the Manual Save for Master Mode is indeed slot 7 :+1:

https://gbatemp.net/threads/botw-transfer-normal-save-to-master-mode.568692/#post-9114275
